import pytest
import numpy as np
from ikfast_solver.ikfast_wrapper import IKFastSolver

@pytest.fixture(scope="module")
def solver():
    """Pytest fixture to initialize the solver once per test module."""
    try:
        return IKFastSolver()
    except Exception as e:
        pytest.fail(f"Failed to initialize IKFastSolver: {e}")

def test_solver_initialization(solver):
    """Tests that the solver initializes and reports the correct number of joints."""
    assert solver is not None
    assert solver.num_joints == 6  # Adjust this number based on your robot

def test_fk_ik_consistency(solver):
    """
    Tests if IK can solve for a pose generated by FK.
    This is a fundamental sanity check.
    """
    # An arbitrary set of joint angles
    joint_angles = np.deg2rad([10, 20, -30, 40, -50, 60])
    
    # 1. Use Forward Kinematics to get the end-effector pose
    fk_translation, fk_rotation = solver.compute_fk(joint_angles)
    fk_rotation_flat = fk_rotation.flatten()

    assert fk_translation is not None, "FK calculation failed"

    # 2. Use Inverse Kinematics to solve for that pose
    # We use the original angles as the initial guess to get the same solution back
    ik_solution = solver.solve_ik(fk_translation, fk_rotation_flat, joint_angles)

    assert ik_solution is not None, "IK solution not found for a valid FK pose"
    
    # 3. Check if the IK solution is very close to the original joint angles
    assert np.allclose(joint_angles, ik_solution, atol=1e-6), "FK -> IK -> FK round trip failed"

def test_batch_solver(solver):
    """Tests the high-performance batch solver on a short path."""
    # Define joint-space waypoints that stay within the known limits
    waypoints = np.array([
        np.zeros(solver.num_joints),
        np.array([0.05, -0.05, 0.03, 0.01, -0.01, 0.0]),
        np.array([0.1, -0.1, 0.06, 0.02, -0.02, 0.01]),
    ])

    # Convert to Cartesian poses (translation + rotation matrix flattened)
    poses_batch = np.zeros((len(waypoints), 12))
    for idx, joint_angles in enumerate(waypoints):
        trans, rot = solver.compute_fk(joint_angles)
        poses_batch[idx, :3] = trans
        poses_batch[idx, 3:] = rot.flatten()

    path_solutions = solver.solve_ik_path(poses_batch, waypoints[0])

    assert path_solutions is not None, "Batch solver failed to find a solution"
    assert path_solutions.shape == (len(waypoints), solver.num_joints), "Batch solver returned incorrect shape"
    # Confirm the solver follows the intended joint-space path
    assert np.allclose(path_solutions[-1], waypoints[-1], atol=1e-5), "Batch solver deviated from expected joint configuration"
