import pytest
import numpy as np
from ikfast_solver.ikfast_wrapper import IKFastSolver
from gradient_os import ik_solver

@pytest.fixture(scope="module")
def solver():
    """Pytest fixture to initialize the solver once per test module."""
    try:
        return IKFastSolver()
    except Exception as e:
        pytest.fail(f"Failed to initialize IKFastSolver: {e}")

def test_solver_initialization(solver):
    """Tests that the solver initializes and reports the correct number of joints."""
    assert solver is not None
    assert solver.num_joints == 6  # Adjust this number based on your robot

def test_fk_ik_consistency(solver):
    """
    Tests if IK can solve for a pose generated by FK.
    This is a fundamental sanity check.
    """
    # An arbitrary set of joint angles
    joint_angles = np.deg2rad([10, 20, -30, 40, -50, 60])
    
    # 1. Use Forward Kinematics to get the end-effector pose
    fk_translation, fk_rotation = solver.compute_fk(joint_angles)
    fk_rotation_flat = fk_rotation.flatten()

    assert fk_translation is not None, "FK calculation failed"

    # 2. Use Inverse Kinematics to solve for that pose
    # We use the original angles as the initial guess to get the same solution back
    ik_solution = solver.solve_ik(fk_translation, fk_rotation_flat, joint_angles)

    assert ik_solution is not None, "IK solution not found for a valid FK pose"
    
    # 3. Check if the IK solution is very close to the original joint angles
    assert np.allclose(joint_angles, ik_solution, atol=1e-6), "FK -> IK -> FK round trip failed"

def test_batch_solver(solver):
    """Tests the high-performance batch solver on a short path."""
    # Define joint-space waypoints that stay within the known limits
    waypoints = np.array([
        np.zeros(solver.num_joints),
        np.array([0.05, -0.05, 0.03, 0.01, -0.01, 0.0]),
        np.array([0.1, -0.1, 0.06, 0.02, -0.02, 0.01]),
    ])

    # Convert to Cartesian poses (translation + rotation matrix flattened)
    poses_batch = np.zeros((len(waypoints), 12))
    for idx, joint_angles in enumerate(waypoints):
        trans, rot = solver.compute_fk(joint_angles)
        poses_batch[idx, :3] = trans
        poses_batch[idx, 3:] = rot.flatten()

    path_solutions = solver.solve_ik_path(poses_batch, waypoints[0])

    assert path_solutions is not None, "Batch solver failed to find a solution"
    assert path_solutions.shape == (len(waypoints), solver.num_joints), "Batch solver returned incorrect shape"
    # Confirm the solver follows the intended joint-space path
    assert np.allclose(path_solutions[-1], waypoints[-1], atol=1e-5), "Batch solver deviated from expected joint configuration"


def test_backend_pose_adapter_ikfast_uses_wrist_target():
    target_pos = np.array([0.42, -0.05, 0.31], dtype=float)
    target_rot = np.eye(3, dtype=float)

    adapted_pos, adapted_rot = ik_solver._prepare_backend_target_pose(
        target_pos, target_rot, "ikfast"
    )
    expected_pos = target_pos - ik_solver.END_EFFECTOR_OFFSET

    assert np.allclose(adapted_pos, expected_pos, atol=1e-12)
    assert np.allclose(adapted_rot, target_rot, atol=1e-12)


def test_backend_pose_adapter_numeric_uses_tool_target_directly():
    target_pos = np.array([0.42, -0.05, 0.31], dtype=float)
    target_rot = np.eye(3, dtype=float)

    adapted_pos, adapted_rot = ik_solver._prepare_backend_target_pose(
        target_pos, target_rot, "numeric"
    )

    assert np.allclose(adapted_pos, target_pos, atol=1e-12)
    assert np.allclose(adapted_rot, target_rot, atol=1e-12)


def test_batch_preparation_matches_single_pose_adapter(monkeypatch):
    class _CaptureSolver:
        def __init__(self):
            self.last_batch = None

        def solve_ik_path(self, poses_batch, initial_joint_angles):
            self.last_batch = np.asarray(poses_batch, dtype=float)
            return np.zeros((len(poses_batch), 6), dtype=float)

    capture_solver = _CaptureSolver()
    target_pos = [0.25, 0.10, 0.20]
    target_rot = np.eye(3, dtype=float)

    original_backend = ik_solver._BACKEND_NAME
    original_solver = ik_solver.IK_SOLVER
    try:
        for backend_name in ("ikfast", "numeric"):
            monkeypatch.setattr(ik_solver, "_BACKEND_NAME", backend_name)
            monkeypatch.setattr(ik_solver, "IK_SOLVER", capture_solver)
            ik_solver.solve_ik_path_batch([target_pos], initial_joint_angles=[0.0] * 6, target_orientations=[target_rot])
            expected_pos, expected_rot = ik_solver._prepare_backend_target_pose(target_pos, target_rot, backend_name)
            assert capture_solver.last_batch is not None
            assert np.allclose(capture_solver.last_batch[0, :3], expected_pos, atol=1e-12)
            assert np.allclose(capture_solver.last_batch[0, 3:].reshape(3, 3), expected_rot, atol=1e-12)
    finally:
        monkeypatch.setattr(ik_solver, "_BACKEND_NAME", original_backend)
        monkeypatch.setattr(ik_solver, "IK_SOLVER", original_solver)


def test_batch_solver_output_is_normalized_to_python_lists(monkeypatch):
    class _ArrayReturningSolver:
        def solve_ik_path(self, poses_batch, initial_joint_angles):
            return np.array(
                [
                    [0.1, -0.2, 0.3, -0.4, 0.5, -0.6],
                    [0.2, -0.1, 0.4, -0.3, 0.6, -0.5],
                ],
                dtype=float,
            )

    original_solver = ik_solver.IK_SOLVER
    try:
        monkeypatch.setattr(ik_solver, "IK_SOLVER", _ArrayReturningSolver())
        joint_path = ik_solver.solve_ik_path_batch(
            path_points=[[0.2, 0.0, 0.2], [0.21, 0.0, 0.2]],
            initial_joint_angles=[0.0] * 6,
            target_orientations=[np.eye(3, dtype=float), np.eye(3, dtype=float)],
        )
    finally:
        monkeypatch.setattr(ik_solver, "IK_SOLVER", original_solver)

    assert isinstance(joint_path, list)
    assert joint_path
    assert all(isinstance(point, list) for point in joint_path)
    assert joint_path[0][0] == pytest.approx(0.1)
    assert joint_path[1][-1] == pytest.approx(-0.5)
