from __future__ import annotations

from typing import Any

RTCORE_DRIVE_PROFILE_UNKNOWN = 0
RTCORE_DRIVE_PROFILE_A6EC_DS402 = 1
RTCORE_DRIVE_PROFILE_CIA402 = 2

RTCORE_DRIVE_PROFILE_NAME_TO_ID: dict[str, int] = {
    "a6ec_ds402": RTCORE_DRIVE_PROFILE_A6EC_DS402,
    "cia402": RTCORE_DRIVE_PROFILE_CIA402,
}

RTCORE_DRIVE_PROFILE_ID_TO_NAME: dict[int, str] = {
    value: key for key, value in RTCORE_DRIVE_PROFILE_NAME_TO_ID.items()
}


def normalize_drive_profile_id(profile_id: object | None) -> str | None:
    token = str(profile_id or "").strip().lower()
    if not token:
        return None
    if token.isdigit():
        return RTCORE_DRIVE_PROFILE_ID_TO_NAME.get(int(token))
    return token


def rtcore_drive_profile_name_to_id(profile_id: object | None) -> int:
    token = normalize_drive_profile_id(profile_id)
    if not token:
        return RTCORE_DRIVE_PROFILE_UNKNOWN
    return int(RTCORE_DRIVE_PROFILE_NAME_TO_ID.get(token, RTCORE_DRIVE_PROFILE_UNKNOWN))


def rtcore_drive_profile_id_to_name(profile_code: object | None) -> str | None:
    try:
        code = int(profile_code)
    except Exception:
        return None
    return RTCORE_DRIVE_PROFILE_ID_TO_NAME.get(code)


def build_rtcore_axis_scaling(robot_config: dict[str, Any]) -> dict[str, Any]:
    counts_per_rev = [int(value) for value in list(robot_config.get("actuator_encoder_counts_per_rev", []))]
    gear_ratios = [float(value) for value in list(robot_config.get("actuator_gear_ratios", []))]
    signs_raw = list(robot_config.get("actuator_position_signs", []))

    num_axes = min(
        int(robot_config.get("num_physical_actuators", min(len(counts_per_rev), len(gear_ratios)))),
        len(counts_per_rev),
        len(gear_ratios),
    )
    if num_axes <= 0:
        raise ValueError("Robot config does not expose valid RTCore axis scaling.")

    signs: list[int] = []
    for idx in range(num_axes):
        raw_sign = int(signs_raw[idx]) if idx < len(signs_raw) else 1
        signs.append(1 if raw_sign >= 0 else -1)

    return {
        "num_axes": num_axes,
        "counts_per_rev": counts_per_rev[:num_axes],
        "gear_ratio": gear_ratios[:num_axes],
        "sign": signs,
    }


def build_rtcore_startup_env(
    *,
    robot_config: dict[str, Any],
    drive_profile: str | None,
) -> dict[str, str]:
    axis_scaling = build_rtcore_axis_scaling(robot_config)
    normalized_profile = normalize_drive_profile_id(drive_profile)
    if normalized_profile and rtcore_drive_profile_name_to_id(normalized_profile) == RTCORE_DRIVE_PROFILE_UNKNOWN:
        raise ValueError(f"Unsupported RTCore drive profile '{drive_profile}'.")

    return {
        "GRADIENT_RT_NUM_AXES": str(int(axis_scaling["num_axes"])),
        "GRADIENT_RT_COUNTS_PER_REV": ",".join(str(int(value)) for value in axis_scaling["counts_per_rev"]),
        "GRADIENT_RT_GEAR_RATIO": ",".join(f"{float(value):g}" for value in axis_scaling["gear_ratio"]),
        "GRADIENT_RT_SIGN": ",".join(str(int(value)) for value in axis_scaling["sign"]),
        "GRADIENT_RT_DRIVE_PROFILE": normalized_profile or "",
    }


def render_rtcore_systemd_env(
    *,
    robot_config: dict[str, Any],
    drive_profile: str | None,
) -> str:
    env = build_rtcore_startup_env(robot_config=robot_config, drive_profile=drive_profile)
    lines = [
        "# Generated by systemd/rt-motion/install.sh",
        "# Regenerate after robot/runtime drive-profile changes.",
    ]
    for key in sorted(env.keys()):
        value = env[key].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key}="{value}"')
    lines.append("")
    return "\n".join(lines)
